+incdir+../harness
+incdir+.
+incdir+env
+incdir+sequences
+incdir+tests
+incdir+tb
+incdir+assertions
../harness/apb_if.sv
../harness/spi_if.sv
../golden_rtl/spi_core.sv
../golden_rtl/apb_regfile.sv
../golden_rtl/spi_master.sv
../harness/dut_wrapper.sv
assertions/spi_sva.sv
env/apb_agent_pkg.sv
env/spi_agent_pkg.sv
env/spi_pkg.sv
sequences/spi_seq_pkg.sv
tests/spi_test_pkg.sv
tb/tb_top.sv
